"""Initial migration

Revision ID: bf123ce58715
Revises: 
Create Date: 2023-11-16 10:18:17.973691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf123ce58715'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_food')
    op.drop_table('food')
    with op.batch_alter_table('bug', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=2500), nullable=False))
        batch_op.drop_column('proteins')
        batch_op.drop_column('carbs')
        batch_op.drop_column('fats')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bug', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fats', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('carbs', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('proteins', sa.INTEGER(), nullable=False))
        batch_op.drop_column('description')

    op.create_table('food',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('proteins', sa.INTEGER(), nullable=False),
    sa.Column('carbs', sa.INTEGER(), nullable=False),
    sa.Column('fats', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('log_food',
    sa.Column('log_id', sa.INTEGER(), nullable=False),
    sa.Column('food_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['log_id'], ['log.id'], ),
    sa.PrimaryKeyConstraint('log_id', 'food_id')
    )
    # ### end Alembic commands ###
